### ISSUE TITLE
AUR package -- license?

### ISSUE THREAD

**Issue by mserajnik** [flubberding/ProtonUpdater#2]
Hey,

thank you for this tool. I made a simple PKGBUILD for it and published it in the AUR: https://aur.archlinux.org/packages/cproton-git/

Mainly because this makes it even easier to use and update (I prefer having as much as possible handled by pacman and my AUR helper).

I intend to keep maintaining this, but I'm also willing to add you as co-maintainer or hand over the control altogether (if you'd prefer to maintain it yourself).

Since I couldn't find a license on this repo, I've used `unknown` for now. As suggested [here](https://wiki.archlinux.org/index.php/PKGBUILD#license) (_[…] upstream should be contacted about the conditions under which the software is (and is not) available_) I'm reaching out to you to ask if you'd like me to put a specific license in the PKBUILD.

Thank you.

**Comment by flubberding** [comment]
Hey mserajnik!

I haven't really thought about a license yet, as I posted the script out of nowhere. However, I'm totally fine with anyone republishing, modifying or using the code in any way. I'll look into what specific license is best for this situation soon, although I'm very busy at the moment (any suggestions? Deeper dives into licenses are new to me).

Thank you for your contributions by making the PKGBUILD and publishing it in AUR! This will certainly help some users. I'm also  fine with you maintaining the AUR, especially as I don't run an Arch(-based) system (yet).

Flubberding

**Comment by mserajnik** [comment]
Hey,

thanks for the reply.

MIT is probably the most widely-used open source license and allows anyone to republish and modify with minimal conditions. I think it's certainly a good choice for this project. :)

Thanks

Michael

**Comment by flubberding** [comment]
Thanks for your input. MIT License is added :)

**Comment by mserajnik** [comment]
Thanks, I've updated the PKGBUILD accordingly as well: https://aur.archlinux.org/cgit/aur.git/commit/?h=cproton-git&id=5452e1560c44b93302154fe0c7efec22cc1c19cd
