### ISSUE TITLE
Download Error for 6.9-GE-1

### ISSUE THREAD

**Issue by ThisNekoGuy** [flubberding/ProtonUpdater#9]
```
Proton 6.9-GE-1 is the latest version and is not installed yet.
Do you want to try to download and (re)install this release? <y/N> y

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Do you want to delete intalled versions? <y/N> n
Do you want to restart Steam? <y/N> n

```

**Comment by kkleinw** [comment]
The current version of the script downloads the first file from the release page, which is the sha512sum file. See my pull request for a fix.

**Comment by flubberding** [comment]
Hi!

Thanks for reporting this issue. 
The commit of @kkleinw has been merged with the repo and it should be working now. Just make sure to download the latest commit :)
